apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-k8-deployment
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 2
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: angular-k8:1.0
        ports:
        - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  name: angular-service
spec:
  selector:
    app: angular
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort